# Some people have reported problems with the balrogui-py3 API proxy not working correctly.
# This appears to be the same problem reported in https://github.com/docker/compose/issues/2172,
# and seems to only occur with certain(older) versions of docker-compose.
version: '2.1'
services:
  balrogadmin-py3:
    build:
      context: .
      dockerfile: Dockerfile.py3.dev
    depends_on:
      balrogdb-py3:
        condition: service_healthy
    entrypoint:
      - bash
      - scripts/initdb_and_run.sh
    command: admin
    expose:
      - "17070"
    volumes:
      - .:/app
    links:
      - balrogdb-py3
    environment:
      - DBURI=mysql://balrogadmin:balrogadmin@balrogdb-py3/balrog
      - DB_HOST=balrogdb-py3
      - CACHEDIR=.cache_py3
      - SECRET_KEY=blahblah
      - PORT=17070
      - LOG_FORMAT=plain
      - LOG_LEVEL=WARNING
      - INSECURE_SESSION_COOKIE=1
      - LOCALDEV=1
      # Grab mail information from the local environment
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_TLS
      - NOTIFY_TO_ADDR
      - NOTIFY_FROM_ADDR
      - STAGING
    healthcheck:
        test: nc -z -v balrogadmin-py3 17070
        interval: 5s
        timeout: 30s
        retries: 50


  balrogpub-py3:
    build:
      context: .
      dockerfile: Dockerfile.py3.dev
    depends_on:
      balrogdb-py3:
        condition: service_healthy
    command: public
    ports:
      - "19090:19090"
    volumes:
      - .:/app
    environment:
      - DBURI=mysql://balrogadmin:balrogadmin@balrogdb-py3/balrog
      - SECRET_KEY=blahblah
      - PORT=19090
      - LOG_FORMAT=plain
      - LOG_LEVEL=WARNING
    links:
      - balrogdb-py3


  balrogagent-py3:
    build: ./agent
    depends_on:
      nginx-py3:
        condition: service_healthy
    volumes:
      - ./agent:/app
    links:
      - nginx-py3
    environment:
      - BALROG_API_ROOT=http://nginx-py3:18081/api
      - BALROG_USERNAME=balrogagent
      - BALROG_PASSWORD=na
      - TELEMETRY_API_ROOT=abc
      - LOG_FORMAT=plain
      - LOG_LEVEL=WARNING


  # This container exists solely to have something automatically rebuilding the UI
  # in the background during local development. Although it runs a web server, we
  # don't use it. Instead, the nginx one below is used as our entry point to more
  # closely mimic production, and support SSL.
  balrogui-py3:
    image: node:0.10
    depends_on:
      balrogadmin-py3:
        condition: service_healthy
    volumes:
      - ./ui:/app
      - .cache_py3:/cache
    environment:
      - WEB_PORT=16060
      - HOST_PROXY=balrogadmin-py3
      - HOST_PROXY_PORT=17070
    entrypoint:
      - /bin/bash
      - /app/docker-entrypoint.sh


  nginx-py3:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "18080:18080"
      - "18081:18081"
    links:
      - balrogadmin-py3
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/http_balrog.conf.template
      - ./scripts/server.crt:/etc/nginx/server.crt
      - ./scripts/server.key:/etc/nginx/server.key
      - ./scripts/dhparam.pem:/etc/nginx/dhparam.pem
    environment:
      - NGINX_PORT=18080
      - NGINX_BALROG_AGENT_PORT=18081
      - BALROG_ADMIN_ROOT=http://balrogadmin-py3:17070
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_BALROG_AGENT_PORT $$BALROG_ADMIN_ROOT' < /etc/nginx/conf.d/http_balrog.conf.template > /etc/nginx/conf.d/http_balrog.conf && nginx -g 'daemon off;'"
    healthcheck:
        test: nc -z -v nginx 18080 && nc -z -v nginx 18081
        interval: 5s
        timeout: 30s
        retries: 50


  balrogdb-py3:
    build:
      context: .
      dockerfile: Dockerfile.database
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=balrog
      - MYSQL_USER=balrogadmin
      - MYSQL_PASSWORD=balrogadmin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - .cache_py3/mysql:/var/lib/mysql
    healthcheck:
        test: nc -z -v balrogdb-py3 3306
        interval: 30s
        timeout: 30s
        retries: 10
